### ISSUE TITLE
Benchmark configuration file

### ISSUE THREAD

**Issue by nirs** [nirs/vmnet-helper#47]
Replace the benchmark command line options with configuration file describing a benchmark run.

## Example configuration

```yaml
modes:
- shared
- bridged
- host
shared-interface: en10
time: 30
drivers:
- name: krunkit
- name: krunkit
  tag: nooffload
  command: /Users/user/bin/krunkit
  offload: false
- name: vfkit
- name: qemu
tests:
- host-to-vm
- vm-to-host
- vm-to-vm
```

The benchmark will run:
- Standard krunkit driver
- krunkit driver with overrides
  - custom command
  - storing results as krunkit:nooffload
  - disable offloading
- Standard vfkit driver

We can keep several configurations for different purposes.

Same or similar configuration can be used to create plots. The plot tool will consider only the configured drivers, tests, and modes.
