### ISSUE TITLE
alpine example vm does not get ip address after first boot, changes ip adress

### ISSUE THREAD

**Issue by nirs** [nirs/vmnet-helper#54]
Unlike ubuntu and fedora vms, that get ip address in few seconds, and keep the same ip address, the alpine vm get new ip address for every new vm, and does not get an ip address after the first boot.

The reason seems to be that the vm is using respecting the `dhcp-identifier: mac` network-config:

```
% cat ~/.vmnet-helper/vms/alpine/network-config 
version: 2
ethernets:
  vmnet0:
    match:
      macaddress: ca:4b:5e:6f:9c:86
    set-name: vmnet0
    dhcp4: true
    dhcp-identifier: mac
```

Because we in var/db/dhcpd_leases that every vm creates a new leases with the VM UUID instead of the mac address:

```
% cat /var/db/dhcpd_leases
{
	name=alpine
	ip_address=192.168.105.10
	hw_address=ff,5e:6f:9c:86:0:1:0:1:2f:4e:92:af:ca:4b:5e:6f:9c:86
	identifier=ff,5e:6f:9c:86:0:1:0:1:2f:4e:92:af:ca:4b:5e:6f:9c:86
	lease=0x67bbd915
}
{
	name=alpine
	ip_address=192.168.105.9
	hw_address=ff,5e:6f:9c:86:0:1:0:1:2f:4e:8b:51:ca:4b:5e:6f:9c:86
	identifier=ff,5e:6f:9c:86:0:1:0:1:2f:4e:8b:51:ca:4b:5e:6f:9c:86
	lease=0x67bbd1d5
}
{
	name=alpine
	ip_address=192.168.105.8
	hw_address=ff,5e:6f:9c:86:0:1:0:1:2f:4e:87:d1:ca:4b:5e:6f:9c:86
	identifier=ff,5e:6f:9c:86:0:1:0:1:2f:4e:87:d1:ca:4b:5e:6f:9c:86
	lease=0x67bbcece
}
{
	name=alpine
	ip_address=192.168.105.7
	hw_address=ff,5e:6f:9c:86:0:1:0:1:2f:4e:7f:3d:ca:4b:5e:6f:9c:86
	identifier=ff,5e:6f:9c:86:0:1:0:1:2f:4e:7f:3d:ca:4b:5e:6f:9c:86
	lease=0x67bbc515
}
{
	name=alpine
	ip_address=192.168.105.6
	hw_address=1,ca:4b:5e:6f:9c:86
	identifier=1,ca:4b:5e:6f:9c:86
	lease=0x67bbc3f1
}
{
	name=fedora
	ip_address=192.168.105.5
	hw_address=1,ea:50:7f:9e:22:9b
	identifier=1,ea:50:7f:9e:22:9b
	lease=0x67bbd863
}
{
	name=ubuntu
	ip_address=192.168.105.4
	hw_address=1,82:e9:dd:3d:68:1f
	identifier=1,82:e9:dd:3d:68:1f
	lease=0x67bbd848
}
```

Tasks:
- open alpine bug
